In [1]:
%autosave 1
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

heart_disease = pd.read_csv("resources/heart-disease.csv")
heart_disease.head()

Autosaving every 1 seconds


age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

# 4. Evaluating a model

## 4.1 Evaluating a model with the `score()` method

### 4.2.2 Area under the receiver operating characteristic curve (AUC/ROC)

- Area under curve (AUC).
- ROC curve.

ROC curves are a comparison of a model's true positive rate (tpr) versus a model's false positive rate (fpr).

* **True positive** = Model predicts 1 when truth is 1.
* **False positive** = mModel predicts 1 when truth is 0.
* **True negative** = Model predicts 0 when truth is 0.
* **False negative** = Model predicts 0 when truth is 1.

In [8]:
# Prepare data
X = heart_disease.drop("target", axis=1)
y = heart_disease["target"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Import the model
from sklearn.ensemble import RandomForestClassifier

# Instatiate the model
clf = RandomForestClassifier();

# Fit the model
clf.fit(X_train, y_train)

from sklearn.metrics import roc_curve

# Make predictions with probabilities
y_probs = clf.predict_proba(X_test)
y_probs[:10]

array([[0.45, 0.55],
       [0.71, 0.29],
       [0.19, 0.81],
       [0.96, 0.04],
       [0.78, 0.22],
       [0.13, 0.87],
       [0.17, 0.83],
       [0.43, 0.57],
       [0.17, 0.83],
       [0.65, 0.35]])

In [9]:
y_probs_positive = y_probs[:, 1]
y_probs_positive[:10]

array([0.55, 0.29, 0.81, 0.04, 0.22, 0.87, 0.83, 0.57, 0.83, 0.35])

#### Calculate fpr, tpr and thresholds

**fpr** - Increasing false positive rate.
**tpr** - Increasing true positive rate.
**thresholds** - Decreasing limite used by fpr and tpr.

In [12]:
fpr, tpr, thresholds = roc_curve(y_test, y_probs_positive)

#### Check fpr

In [13]:
fpr

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.03030303, 0.03030303, 0.03030303, 0.03030303,
       0.06060606, 0.09090909, 0.09090909, 0.12121212, 0.12121212,
       0.18181818, 0.18181818, 0.21212121, 0.21212121, 0.24242424,
       0.3030303 , 0.33333333, 0.39393939, 0.48484848, 0.48484848,
       0.51515152, 0.51515152, 0.66666667, 0.75757576, 0.84848485,
       0.90909091, 0.93939394, 1.        ])