In [6]:
%autosave 1

import pandas as pd
import numpy as np

a1 = np.array([1, 2, 3])
a2 = np.array([[1, 2, 3.3],
              [4, 5, 6.5]])

Autosaving every 1 seconds


In [7]:
a1

array([1, 2, 3])

In [8]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

# Comparison operators

In [11]:
# Checks if each elements of the first array is greater than each element of the matrix.
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [13]:
bool_array = a1 >= a2
bool_array

array([[ True,  True, False],
       [False, False, False]])

In [14]:
type(bool_array), bool_array.dtype

(numpy.ndarray, dtype('bool'))

In [15]:
a1 > 5

array([False, False, False])

In [16]:
a1 < 5

array([ True,  True,  True])

In [17]:
a1 == a1

array([ True,  True,  True])

In [18]:
a1 == a2

array([[ True,  True, False],
       [False, False, False]])

> There are also the functions equivalent to those operators.