In [1]:
%autosave 1
import numpy as np

Autosaving every 1 seconds


# Creating arrays

In [2]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [3]:
sample_array.dtype

dtype('int32')

> **Shift** + **Tab** displays the function's signature

## Array filled with 1s or 0s

- Basically, placeholder arrays.

In [7]:
ones = np.ones((2, 4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
ones.dtype

dtype('float64')

In [9]:
type(ones)

numpy.ndarray

In [10]:
zeros = np.zeros((2, 4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
zeros.dtype

dtype('float64')

In [13]:
type(zeros)

numpy.ndarray

## Array with numbers within a range

- By default it returns 5 numbers.
- Default step is 1.

In [16]:
range_array = np.arange(1.2, 10.4)
range_array

array([ 1.2,  2.2,  3.2,  4.2,  5.2,  6.2,  7.2,  8.2,  9.2, 10.2])

## Array with random integers numbers within a range

In [20]:
random_array = np.random.randint(2, 10, size=(3, 5))
random_array

array([[8, 4, 8, 6, 8],
       [7, 6, 3, 6, 5],
       [8, 4, 8, 9, 5]])

## Array with random float numbers

In [22]:
random_float_array = np.random.random((5, 3))
random_float_array

array([[0.69469716, 0.50310828, 0.98589573],
       [0.93009526, 0.90313726, 0.79123023],
       [0.92720766, 0.6437017 , 0.075873  ],
       [0.09719318, 0.33562381, 0.28998303],
       [0.48860769, 0.54658728, 0.67785587]])

In [24]:
random_float_array_2 = np.random.rand(5, 3)
random_float_array_2

array([[0.30559687, 0.72030531, 0.79718371],
       [0.36331972, 0.70659115, 0.07642481],
       [0.00897948, 0.81522728, 0.92114401],
       [0.65122084, 0.72497595, 0.77101085],
       [0.54913072, 0.39387057, 0.41054731]])