In [9]:
%autosave 1

import numpy as np

np.random.seed(0)
mat1 = np.random.randint(100, size=(5, 3))
mat2 = np.random.randint(100, size=(5, 3))

Autosaving every 1 seconds


In [10]:
mat1

array([[44, 47, 64],
       [67, 67,  9],
       [83, 21, 36],
       [87, 70, 88],
       [88, 12, 58]])

In [11]:
mat2

array([[65, 39, 87],
       [46, 88, 81],
       [37, 25, 77],
       [72,  9, 20],
       [80, 69, 79]])

# Hadamard product

In [13]:
mat1 * mat2

array([[2860, 1833, 5568],
       [3082, 5896,  729],
       [3071,  525, 2772],
       [6264,  630, 1760],
       [7040,  828, 4582]])

# Dot product

- Multiplies the rows of the first matrix by the columns of the second. Because of that, the number of rows of the first matrix must be equal to the number of columns of the second.

![dot-product](resources/dot-product.png)

In [17]:
mat1.shape, mat2.T.shape

((5, 3), (3, 5))

In [16]:
# One of the situations where you would use transpose.
np.dot(mat1, mat2.T)

array([[10261, 11344,  7731,  4871, 11819],
       [ 7751,  9707,  4847,  5607, 10694],
       [ 9346,  8582,  6368,  6885, 10933],
       [16041, 17290, 11745,  8654, 18742],
       [11234,  9802,  8022,  7604, 12450]])