In [9]:
%autosave 1

import pandas as pd
import numpy as np

Autosaving every 1 seconds


# Dot product example (nut butter sales)

In [7]:
np.random.seed(0)

# Numbers of jars sold
sales_amounts = np.random.randint(20, size=(5, 3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [12]:
# Create weekly_sales DataFrame
weekly_sales = pd.DataFrame(sales_amounts, index=["Mon", "Tues", "Wed", "Thurs", "Fri"], columns=["Almond butter", "Peanut butter", "Cashew butter"])
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [14]:
# Create the prices array
prices = np.array([10, 8, 12])
prices

array([10,  8, 12])

### NumPy problem

When working with 1-dimensional array, you have to reshape in order to use.

In [21]:
prices.shape

(3,)

In [24]:
prices.reshape(1,3)

array([[10,  8, 12]])

In [20]:
# Create butter_prices DataFrame
butter_prices = pd.DataFrame(prices.reshape(1,3), 
                            index=["Price"],
                            columns=["Almond butter", "Peanut butter", "Cashew butter"])
butter_prices

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [27]:
# Transposing because sales weren't aligned.
total_sales = prices.dot(sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])

In [30]:
# Making use of transpose again.
weekly_sales["Total ($)"] = total_sales.T
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total ($)
Mon               12             15              0        240
Tues               3              3              7        138
Wed                9             19             18        458
Thurs              4              6             12        232
Fri                1              6              7        142