In [28]:
%autosave 1
import numpy as np

a1 = np.random.randint(1, 10, size=10)
a2 = np.random.randint(10, size=(2, 10))
ones = np.ones(10)

Autosaving every 1 seconds


In [29]:
a1

array([9, 4, 6, 3, 6, 5, 8, 2, 6, 2])

In [30]:
a2

array([[1, 2, 0, 7, 1, 7, 3, 5, 8, 1],
       [7, 1, 9, 8, 5, 8, 5, 0, 6, 4]])

# Manipulating & comparing arrays

> All arrays have to have the same size.
- The term broadcasting describes how numpy treats arrays with different shapes during airithmetic operation.

## Arithmetic

In [31]:
a1 + ones

array([10.,  5.,  7.,  4.,  7.,  6.,  9.,  3.,  7.,  3.])

In [32]:
a1 - ones

array([8., 3., 5., 2., 5., 4., 7., 1., 5., 1.])

In [33]:
a1 * ones

array([9., 4., 6., 3., 6., 5., 8., 2., 6., 2.])

In [34]:
a1 * a2

array([[ 9,  8,  0, 21,  6, 35, 24, 10, 48,  2],
       [63,  4, 54, 24, 30, 40, 40,  0, 36,  8]])

In [36]:
a2 / a1

array([[0.11111111, 0.5       , 0.        , 2.33333333, 0.16666667,
        1.4       , 0.375     , 2.5       , 1.33333333, 0.5       ],
       [0.77777778, 0.25      , 1.5       , 2.66666667, 0.83333333,
        1.6       , 0.625     , 0.        , 1.        , 2.        ]])

In [38]:
# Floor division
a2 // a1

array([[0, 0, 0, 2, 0, 1, 0, 2, 1, 0],
       [0, 0, 1, 2, 0, 1, 0, 0, 1, 2]])

In [40]:
# To the power of
a2 ** a1

array([[       1,       16,        0,      343,        1,    16807,
            6561,       25,   262144,        1],
       [40353607,        1,   531441,      512,    15625,    32768,
          390625,        0,    46656,       16]])

In [41]:
# NumPy also has the equivalent functions for the operators.
np.square(a1)

array([81, 16, 36,  9, 36, 25, 64,  4, 36,  4])

In [43]:
a2 % a1

array([[1, 2, 0, 1, 1, 2, 3, 1, 2, 1],
       [7, 1, 3, 2, 5, 3, 5, 0, 0, 0]])

In [45]:
np.log(a1)

array([2.19722458, 1.38629436, 1.79175947, 1.09861229, 1.79175947,
       1.60943791, 2.07944154, 0.69314718, 1.79175947, 0.69314718])

In [46]:
np.exp(a2)

array([[2.71828183e+00, 7.38905610e+00, 1.00000000e+00, 1.09663316e+03,
        2.71828183e+00, 1.09663316e+03, 2.00855369e+01, 1.48413159e+02,
        2.98095799e+03, 2.71828183e+00],
       [1.09663316e+03, 2.71828183e+00, 8.10308393e+03, 2.98095799e+03,
        1.48413159e+02, 2.98095799e+03, 1.48413159e+02, 1.00000000e+00,
        4.03428793e+02, 5.45981500e+01]])