In [4]:
%autosave 1
import numpy as np

Autosaving every 1 seconds


# DataTypes & Attributes


## ndarray
NumPy's main datatype is **ndarray** (n-dimensional array).

![numpyarray](resources/numpyarray.png)

In [5]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [6]:
type(a1)

numpy.ndarray

In [7]:
a2 = np.array([[1, 2.0, 3.3],
              [4, 5, 6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [8]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

## Identifying how many dimensions and rows there are

- According to the number of dimensions we have a number dispalyed.

In [9]:
a1.shape

(3,)

In [10]:
a2.shape

(2, 3)

In [11]:
a3.shape

(3, 2, 3)

## Identiying only the number of dimensions

In [12]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

## Types

Note that it can only have one type of datatype, so what doesn't fit gets converted to a datatype more that can fit them all.

In [13]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [15]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

## Number of elements in each ndarray

In [14]:
a1.size, a2.size, a3.size

(3, 6, 18)

## Creating a DataFrame from a NumPy array

- Pandas is built on top of NumPy making conversions really easy.- 

In [18]:
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5