In [1]:
%autosave 1
import numpy as np

Autosaving every 1 seconds


# Pseudo-random numbers

- We can use the seed function to set a seed that wil be used by the random function.

In [6]:
np.random.seed(0)
random_array = np.random.randint(10, size=(5, 3))
random_array

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [14]:
np.random.seed(0)
random_array = np.random.randint(10, size=(5, 3))
random_array

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [11]:
np.random.seed(0)
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606]])

In [13]:
np.random.seed(0)
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606]])

In [4]:
random_array.shape

(5, 3)