In [19]:
%autosave 1
import numpy as np

a1 = np.random.randint(100, size=(10, 5, 5))
a2 = np.random.randint(100, size=(5, 5, 5, 2))
a1

Autosaving every 1 seconds


array([[[91,  7, 67, 96, 82],
        [99, 96, 30, 86, 31],
        [28, 69, 62, 67, 20],
        [98, 80, 99,  3, 98],
        [ 0, 16, 36, 22, 15]],

       [[65, 57, 89, 38,  4],
        [ 7, 49, 27, 66, 99],
        [ 3, 71, 54,  8, 51],
        [16, 99, 99, 22, 25],
        [17, 80, 53,  2, 14]],

       [[58, 76, 28, 95, 50],
        [88, 56,  5, 34, 91],
        [46,  3, 64, 14, 59],
        [55, 48, 85, 66, 38],
        [21, 35, 66,  8, 79]],

       [[46, 66, 10, 19, 80],
        [79, 34, 94, 32, 15],
        [31, 96, 66, 97, 72],
        [ 1, 30, 10,  3, 84],
        [92, 12, 95, 92, 78]],

       [[32, 30, 97, 11, 66],
        [88, 37, 22, 79, 14],
        [53,  3, 45, 53, 42],
        [99,  2, 69, 52, 40],
        [55,  0, 89,  4, 31]],

       [[47, 96, 80, 45, 54],
        [ 5, 99, 80, 66, 34],
        [45, 20, 54, 67,  9],
        [66, 83,  4, 87, 57],
        [30, 78, 96, 55, 78]],

       [[41, 35, 56, 21, 37],
        [61,  3,  1, 25, 28],
        [78,  3, 99, 97, 53]

# Reshaping

- For reshaping an array the multiplication of its dimensions have to be the same as the original one.

In [17]:
a1_reshape = a1.reshape(5, 5, 5, 2)

In [20]:
a1_reshape * a2

array([[[[6480, 4615],
         [8645,  264],
         [5762,  960],
         [   0, 3920],
         [2208, 4180]],

        [[  22, 4840],
         [2870,  355],
         [1125,   66],
         [1856, 2142],
         [8554, 3910]],

        [[1071, 1092],
         [6570, 1775],
         [ 174, 2475],
         [  24,  902],
         [   0, 2886]],

        [[ 924, 1325],
         [1932, 3478],
         [5782,  196],
         [5429, 4872],
         [1584, 1014]],

        [[3534,   99],
         [6715, 8148],
         [2632, 1050],
         [1188, 5310],
         [1053, 2002]]],


       [[[2788, 1581],
         [ 567, 6958],
         [ 480, 8217],
         [6486,  496],
         [3111, 4800]],

        [[3384,    7],
         [3854,   78],
         [5856, 1407],
         [4088, 2240],
         [3960, 3560]],

        [[4672,  220],
         [2700, 8613],
         [1794, 2592],
         [ 360, 3658],
         [ 473, 5544]],

        [[ 930, 4480],
         [1216, 4455],
         [4824, 

# Transposing

- It switches the axis'.

In [22]:
a1.shape

(10, 5, 5)

In [21]:
a1.T

array([[[91, 65, 58, 46, 32, 47, 41, 41, 74, 13],
        [99,  7, 88, 79, 88,  5, 61, 64, 96, 58],
        [28,  3, 46, 31, 53, 45, 78,  7, 99, 45],
        [98, 16, 55,  1, 99, 66, 85, 49, 83, 74],
        [ 0, 17, 21, 92, 55, 30, 88, 30, 82, 28]],

       [[ 7, 57, 76, 66, 30, 96, 35, 31, 86, 50],
        [96, 49, 56, 34, 37, 99,  3, 20, 81, 39],
        [69, 71,  3, 96,  3, 20,  3, 50, 44, 48],
        [80, 99, 48, 30,  2, 83, 44, 70, 21, 72],
        [16, 80, 35, 12,  0, 78, 55, 53, 26, 76]],

       [[67, 89, 28, 10, 97, 80, 56, 99,  4, 86],
        [30, 27,  5, 94, 22, 80,  1,  6, 15, 19],
        [62, 54, 64, 66, 45, 54, 99,  4, 92, 60],
        [99, 99, 85, 10, 69,  4,  6, 49, 68, 83],
        [36, 53, 66, 95, 89, 96, 41, 90, 24, 16]],

       [[96, 38, 95, 19, 11, 45, 21, 34, 48, 77],
        [86, 66, 34, 32, 79, 66, 25,  3, 20,  8],
        [67,  8, 14, 97, 53, 67, 97, 96, 61,  4],
        [ 3, 22, 66,  3, 52, 87, 11, 71, 20, 56],
        [22,  2,  8, 92,  4, 55, 12,  5, 90,

In [23]:
a1.T.shape

(5, 5, 10)