In [2]:
%autosave 1

import pandas as pd
import numpy as np

random_array = np.random.randint(10, size=(3, 5))

Autosaving every 1 seconds


In [3]:
random_array

array([[9, 7, 5, 5, 3],
       [7, 5, 3, 5, 0],
       [2, 0, 0, 9, 9]])

# Sorting arrays

- It sorts the numbers in each row.

## Sorting values

In [4]:
np.sort(random_array)

array([[3, 5, 5, 7, 9],
       [0, 3, 5, 5, 7],
       [0, 0, 2, 9, 9]])

## Sorting indexes

- This creates an array of indexes that would sort the original array.

In [6]:
np.argsort(random_array)

array([[4, 2, 3, 1, 0],
       [4, 2, 1, 3, 0],
       [1, 2, 0, 3, 4]], dtype=int64)

## Getting index of minimum number in an array

In [8]:
np.argmin(random_array[0])

4

## Getting index of maximum number in an array

In [10]:
np.argmax(random_array[0])

0

## Getting index of maximum number in a matrix

In [16]:
# Highest number in each column
np.argmax(random_array, axis=0)

array([0, 0, 0, 2, 2], dtype=int64)

In [15]:
# Highest number in each row
np.argmax(random_array, axis=1)

array([0, 0, 3], dtype=int64)