In [1]:
%autosave 1

import numpy as np

Autosaving every 1 seconds


# Practical Example - NumPy in Action

<img src="resources/panda.png"/>

## Turn an image into a NumPy array

### How does it work?
- Each pixel in the image has a colour value, by getting each one of those values we can put them in a ndarray, and manipulate it as we wish.

In [2]:
from matplotlib.image import imread

panda = imread("resources/panda.png")
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [3]:
type(panda), panda.size, panda.shape, panda.ndim

(numpy.ndarray, 24465000, (2330, 3500, 3), 3)

In [4]:
panda[:5]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.

<img src="resources/car-photo.png">

In [5]:
car = imread("resources/car-photo.png")
car

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.482352

<img src="resources/dog-photo.png"/>

In [6]:
dog = imread("resources/dog-photo.png")
dog

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]],

       [[0.69411767, 0.8039216 , 0.8862745 , 1.        ],
        [0.7019608 , 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49411765, 0.68235296, 0.84313726, 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ]],

       [[0.6901961 , 0.8       , 0.88235295, 1.        ],
        [0.69803923, 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49803922, 0.686274

### Machine Learning Algorithms

- These algorithms work around the numbers in the arrays above. In order to identify something it checks the numbers to see if their values are close to each other.

## Testing stuff out

In [7]:
from PIL import Image as im

In [8]:
dog.size, car.size, panda.size

(993600, 991300, 24465000)

In [9]:
dog.ndim, panda.ndim

(3, 3)

In [10]:
dog.shape, panda.shape

((432, 575, 4), (2330, 3500, 3))

In [11]:
new_img_array = dog + 0.0200
new_img_array

array([[[0.7298039 , 0.8278431 , 0.9023529 , 1.02      ],
        [0.7415686 , 0.8317647 , 0.9062745 , 1.02      ],
        [0.76117647, 0.83568627, 0.9062745 , 1.02      ],
        ...,
        [0.5180392 , 0.7062745 , 0.8592157 , 1.02      ],
        [0.51411766, 0.70235294, 0.8592157 , 1.02      ],
        [0.51411766, 0.70235294, 0.8552941 , 1.02      ]],

       [[0.71411765, 0.82392156, 0.9062745 , 1.02      ],
        [0.7219608 , 0.82392156, 0.9023529 , 1.02      ],
        [0.72588235, 0.8278431 , 0.9023529 , 1.02      ],
        ...,
        [0.5219608 , 0.7062745 , 0.8670588 , 1.02      ],
        [0.51411766, 0.70235294, 0.86313725, 1.02      ],
        [0.51411766, 0.70235294, 0.8592157 , 1.02      ]],

       [[0.7101961 , 0.82      , 0.9023529 , 1.02      ],
        [0.7180392 , 0.82392156, 0.9023529 , 1.02      ],
        [0.72588235, 0.8278431 , 0.9023529 , 1.02      ],
        ...,
        [0.5219608 , 0.7062745 , 0.8670588 , 1.02      ],
        [0.5180392 , 0.706274

In [12]:
data = im.fromarray(new_img_array.astype(np.uint8))
data.save("resources/modified-dog.png")

<img src="resources/modified-dog.png"/>

In [13]:
random_img_array = np.random.randint(255, size=737280)
random_img_array = np.reshape(random_img_array.astype(np.uint8), (1024, 720))
data = im.fromarray(random_img_array)
data.save("resources/random-img.png")

![random-img](resources/random-img.png)

In [14]:
import pandas as pd

random_img_array = np.random.randint(155, size=737280).astype(np.uint8)
random_img_array.sort()
random_img_array = np.reshape(random_img_array, (1024, 720))
data = im.fromarray(random_img_array)
data.save("resources/random-img_2.png")

![random-img](resources/random-img_2.png)